apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argocd-helm
  template:
    metadata:
      labels:
        app: argocd-helm
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80

